title: Pietro Sala
author: Pietro Sala
email: pietro.sala.g@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A professional profile always in the making

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
