title: Pietro Sala
author: Pietro Sala
email: pietro.sala.g@gmail.com
description: A professional profile always in the making

# social links
facebook_username: peter.sala
github_username: PeterSala94

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
